### ISSUE TITLE
Enable Fixed position mode for Stationary base operation

### ISSUE THREAD

**Issue by mooneyj** [Menapia-tech/rtk-broadcaster#1]
When we have a stationary base that's fixed for a long time, and has used a long survey-in time to get it it's position, then it's useful to be able to fix the position so that the survey is not needed to be repeated. 

The F9P ublox module is capable of this see section 3.1.5.5.2 Fixed position in the [manual](https://content.u-blox.com/sites/default/files/ZED-F9P_IntegrationManual_UBX-18010802.pdf). 

This repo uses the [PX4 UBX driver](https://github.com/PX4/PX4-GPSDrivers/blob/main/src/ubx.h) to set the SurveyIn specs. Instead we can send the fixed position configuration. 

We'll need a place to enter the fixed position configuration. Reading these values from a local config file seems reasonable. We could even automatically populate this config file once a survey is complete... That might actually be the best way to read the required parameters from the F9P. There are quite a few involved!!

To configure Fixed mode (CFG-TMODE-MODE=FIXED), the following items are relevant:
CFG-TMODE-MODE Receiver mode (disabled or survey-in or fixed)
CFG-TMODE-POS_TYPE Determines whether the ARP position is given in ECEF or LAT/LON/HEIGHT
CFG-TMODE-ECEF_X ECEF X coordinate of the ARP position
CFG-TMODE-ECEF_Y ECEF Y coordinate of the ARP position
CFG-TMODE-ECEF_Z ECEF Z coordinate of the ARP position
CFG-TMODE-LAT Latitude of the ARP position
CFG-TMODE-LON Longitude of the ARP position
CFG-TMODE-HEIGHT Height of the ARP position
CFG-TMODE-ECEF_X_HP High-precision ECEF X coordinate of the ARP position
CFG-TMODE-ECEF_Y_HP High-precision ECEF Y coordinate of the ARP position
CFG-TMODE-ECEF_Z_HP High-precision ECEF Z coordinate of the ARP position
CFG-TMODE-LAT_HP High-precision latitude of the ARP position
CFG-TMODE-LON_HP High-precision longitude of the ARP position
CFG-TMODE-HEIGHT_HP High-precision height of the ARP position
CFG-TMODE-FIXED_POS_ACC Fixed position 3D accuracy estimate

**Comment by castlemaine22** [comment]
I have created a new branch 'stationary_base' with a solution for this. The code has been tested locally on my laptop but requires pushing to the GCS and testing there.

My solution is to have the script look for a .yaml in the home directory which will contain the fixed position of the base station. If the .yaml is there, fixed position tmode will be activated and assigned the coordinates from the yaml. If the yaml isn't present, then it will initiate a RTK survey like before. 

The easiest way to get a fixed position is using QGC to run a long survey, then save the recorded base position into the yaml. 

TODO:
- Are the 'HP' coordinates actually required? Add in, if so
- Find a way to monitor the RTCM1005 message directly to verify base position 
- Ensure the units are handled correctly, looks ok, but worth checking

**Comment by castlemaine22** [comment]
Issue now closed. Solution has been tested on the GCS. I've added a useful RTCM sniffer python script which prints the messages to terminal, allowing the checking of correct RTK streaming and correct base position.
Note for future - the RTCM1005 messages need to be enabled for USB on the UBLOX config.
